services:
  backend:
    build: ./backend          
    env_file:
      - .env  
    volumes:
      - ./backend:/app 
      - ./backend/logs:/app/logs
    restart: always
    networks:
      - dif-network     

  frontend:
    image: nginx:alpine              
    volumes:
      - ./frontend:/usr/share/nginx/html 
      - ./nginx/frontend.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
    networks:
      - dif-network


  nginx-service:
    image: jonasal/nginx-certbot:latest
    container_name: dif-proxy
    restart: unless-stopped
    environment:
      - CERTBOT_EMAIL=${CERTBOT_UPDATES_RECEIVER}
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/active:/etc/nginx/user_conf.d
      - ./letsencrypt:/etc/letsencrypt
      - ./.htpasswd:/etc/nginx/.htpasswd:ro
    ports:
      - "80:80"
      - "443:443"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - dif-network

networks:
  dif-network:
    driver: bridge
